### ISSUE TITLE
No drops/commands

### ISSUE THREAD

**Issue by BladeofHonor** [HellFirePvP/CustomMobs#17]
Hey! I'm running an adventure minecraft server. During the first 5 minutes of using the plugin, the mobs dropped everything fine, but after i set up a spawner, everything went south. I tried working around this by setting up a complex chain of commands that led to a cutscene and a phatloot chest where the mobs drops would be, only to find that the execute command feature was broken as well. I would love to get any help I could regarding this issue. Thanks.

**Comment by HellFirePvP** [comment]
The reason for this issue is known to me already, however i didn't have the time yet to release the update and do proper testing.

So there will be an update soon that fixxes this.

**Comment by HellFirePvP** [comment]
Along with the other 2 issues: Should be fixxed with 4.1

**Comment by Peashooter101** [comment]
Not fixed, Used version 4.12

**Comment by Peashooter101** [comment]
Mobs do not drop anything indicated, regardless of spawning method.

**Comment by HellFirePvP** [comment]
First, the command gets executed by the console. And it should have all perms, that's why the banned commands exist.

Second, the command /cmob cmd doesn't work as intended, i can reproduce that one, the source of that issue is clear and the bug regarding that is easy to fix. Please don't post full stacktraces into your comment please. Use gist or pastebin instead, they exist for a reason.

Third, if the command execution doesn't work, drops, exp drops, respawning and the "removal from the currently-alive-count of a limited custommob" doesn't work as well since they're handled in the same routine. Meaning that, if one of them doesn't work, it's very likely that the other things don't work as well.

**Comment by HellFirePvP** [comment]
"Fixxed" next version.

**Comment by BladeofHonor** [comment]
will the fixed version be available on my multicraft server panel right away? or will
i have to manually upload it 😁 sorry so many questions

**Comment by HellFirePvP** [comment]
I dunno? I updated it on spigot, so... no idea :P
